# coding: utf-8

"""
    Mindwm API

    This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from MindWM.models.neo4j_change_data_capture_meta_source import Neo4jChangeDataCaptureMetaSource
from typing import Optional, Set
from typing_extensions import Self

class Neo4jChangeDataCaptureMeta(BaseModel):
    """
    Neo4jChangeDataCaptureMeta
    """ # noqa: E501
    operation: StrictStr
    source: Neo4jChangeDataCaptureMetaSource
    timestamp: StrictInt
    tx_event_id: StrictInt = Field(alias="txEventId")
    tx_events_count: StrictInt = Field(alias="txEventsCount")
    tx_id: StrictInt = Field(alias="txId")
    username: StrictStr
    __properties: ClassVar[List[str]] = ["operation", "source", "timestamp", "txEventId", "txEventsCount", "txId", "username"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Neo4jChangeDataCaptureMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Neo4jChangeDataCaptureMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "source": Neo4jChangeDataCaptureMetaSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "timestamp": obj.get("timestamp"),
            "txEventId": obj.get("txEventId"),
            "txEventsCount": obj.get("txEventsCount"),
            "txId": obj.get("txId"),
            "username": obj.get("username")
        })
        return _obj


